#
# Headless service (i.e. one with no load balancing/allows direct access to a
# pod) for mongodb
#
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
