# Release app service
#
# Sets up external access on port 80 to port 3036
apiVersion: v1
kind: Service
metadata:
  labels:
    app: release
  name: release
  namespace: frontend
spec:
  ports:
  - name: release-lb-tcp-3036-80
    port: 80
    protocol: TCP
    targetPort: 3036
  selector:
    app: release
  type: NodePort
